language: generic 
sudo: required
services:
  -docker

before_install:
  - docker build -t thantmyat/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true thantmyat/docker-react npm run test